"""Added meeting_name column

Revision ID: 6ee6f2245e1e
Revises: 
Create Date: 2023-09-12 16:24:13.057642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee6f2245e1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_booking_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_rooms_room_id', table_name='rooms')
    op.drop_index('ix_rooms_room_name', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(), nullable=True),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index('ix_rooms_room_name', 'rooms', ['room_name'], unique=False)
    op.create_index('ix_rooms_room_id', 'rooms', ['room_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('booked_num', sa.INTEGER(), nullable=True),
    sa.Column('start_datetime', sa.DATETIME(), nullable=True),
    sa.Column('end_datetime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index('ix_bookings_booking_id', 'bookings', ['booking_id'], unique=False)
    # ### end Alembic commands ###
